// Code generated by goctl. DO NOT EDIT.
package types

type ExpandReq struct {
	Short string `form:"short"`
}

type ExpandResp struct {
	Url string `json:"url"`
}

type ShortReq struct {
	Url string `form:"url"`
}

type ShortResp struct {
	Short string `json:"short"`
}
